# -*- coding: utf-8 -*-
"""Language_Detection_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1En88PWl-mXATn9rBmsHSBxSElq8BMrTb

# Importing the libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""# Importing the dataset"""

dataset = pd.read_csv('Language Detection.csv')
X = dataset["Text"]
y = dataset["Language"]

dataset["Language"].value_counts()

"""# Label Encoding

"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

"""# Cleaning the texts"""

import re
corpus = []
for text in X:
  text = re.sub(r'[!@#$(), n"%^*?:;~`0-9]', ' ', text)
  text = re.sub(r'[[]]', ' ', text)
  text = text.lower()
  corpus.append(text)

print(corpus)

"""# Creating the Bag of Words Model"""

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()

"""# Splitting the dataset in Training Set and Test Set"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

"""# Training the Model on the Training Set"""

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

"""# Predicting the Test set Results"""

y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

"""# Model Evaluation"""

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)
print("Accuracy is:", ac)

plt.figure(figsize=(15, 10))
sns.heatmap(cm, annot = True)
plt.show()

"""# Predicting with more Data"""

def predict(text):
    x = cv.transform([text]).toarray()
    lang = classifier.predict(x)
    lang = le.inverse_transform(lang)
    print("The langauge is:",lang[0])

predict(" Nature, in the broadest sense, is the natural, physical, material world or universe.")

predict("ಮತ್ತು ಅವರು ನನ್ನನ್ನು ಮದುವೆಯಾಗಲು ಬಯಸಿದ್ದರು ಅವರು ಚಿನ್ನದ ಗಾಡಿಯಲ್ಲಿ ಬಂದಿದ್ದರು ಮತ್ತು ಅವರು ಮೇಲಿನಿಂದ ಕೆಳಕ್ಕೆ ಮತ್ತು ಚಿನ್ನವನ್ನು ಧರಿಸಿದ್ದರು ಮತ್ತು ಏನು ಸಿಲ್ಲಿ ಕನಸು.")

predict("und du weißt, das Beste daran war, als ich in meinem Hochzeitskleid war, das natürlich auch aus Gold war.")